/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.acme.gui;

import br.com.acme.ALManager;
import br.com.acme.AcademicLibrary;
import br.com.acme.Author;
import br.com.acme.Book;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Marcos Kuchak Filho
 */
public class AddBookForm extends javax.swing.JDialog {

    private List<Author> authors;
    private AcademicLibrary library;

    /**
     * Creates new form Book
     *
     * @param parent
     * @param modal
     */
    public AddBookForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        authors = new ArrayList();
        library = ALManager.getInstance();
        initComponents();
        //temporário abaixo
        //Book book = new Book("pt_BR", 121245, (short) 300, "Meu Primeiro Livro", (short) 2018, (byte) 1);
        //library.addPublication(book);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtfTitle = new javax.swing.JTextField();
        jtfVolume = new javax.swing.JTextField();
        jtfYear = new javax.swing.JTextField();
        jtfIsbn = new javax.swing.JTextField();
        jtfLanguage = new javax.swing.JTextField();
        jtfPages = new javax.swing.JTextField();
        jbAddAuthor = new javax.swing.JButton();
        jbOk = new javax.swing.JButton();
        jbClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Book");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Book");

        jLabel2.setText("Title:");

        jLabel3.setText("Year:");

        jLabel4.setText("Volume:");

        jLabel5.setText("Language:");

        jLabel6.setText("ISBN:");

        jLabel7.setText("Pages:");

        jtfTitle.setName("jtfTitle"); // NOI18N

        jtfVolume.setName("jtfVolume"); // NOI18N

        jtfYear.setName("jtfYear"); // NOI18N

        jtfIsbn.setName("jtfIsbn"); // NOI18N

        jtfLanguage.setName("jtfLanguage"); // NOI18N
        jtfLanguage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfLanguageActionPerformed(evt);
            }
        });

        jtfPages.setName("jtfPages"); // NOI18N

        jbAddAuthor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/acme/icons/common/add.png"))); // NOI18N
        jbAddAuthor.setText("Add Author");
        jbAddAuthor.setName("jbAddAuthor"); // NOI18N
        jbAddAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddAuthorActionPerformed(evt);
            }
        });

        jbOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/acme/icons/common/check.png"))); // NOI18N
        jbOk.setText("OK");
        jbOk.setName("jbOk"); // NOI18N
        jbOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOkActionPerformed(evt);
            }
        });

        jbClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/acme/icons/common/close.png"))); // NOI18N
        jbClose.setText("Close");
        jbClose.setName("jbClose"); // NOI18N
        jbClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbAddAuthor)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jtfVolume, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                .addComponent(jtfYear, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jtfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel5)
                        .addGap(20, 20, 20)
                        .addComponent(jtfLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addComponent(jbOk, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfIsbn, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                    .addComponent(jtfPages))))
                        .addGap(66, 66, 66)
                        .addComponent(jbClose)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbAddAuthor)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtfPages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbOk)
                    .addComponent(jbClose))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtfLanguageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfLanguageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfLanguageActionPerformed

    private void jbAddAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddAuthorActionPerformed
        AuthorForm authorForm = new AuthorForm(this, true, authors);
        authorForm.setVisible(true); //exibe o dialog do author
    }//GEN-LAST:event_jbAddAuthorActionPerformed

    private void jbOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOkActionPerformed
        if (validateForm()) {
            return;
        }

        String title = jtfTitle.getText();
        short year = Short.parseShort(jtfYear.getText());
        byte volume = Byte.parseByte(jtfVolume.getText());
        String language = jtfLanguage.getText();
        long isbn = Long.parseLong(jtfIsbn.getText());
        short pages = Short.parseShort(jtfPages.getText());

        Book book = new Book(language, isbn, pages, title, year, volume);
        book.setAuthors(authors);
        library.addPublication(book);

        clearForm();
        GUIMessage.info("Book added successfully.");

    }//GEN-LAST:event_jbOkActionPerformed

    private boolean validateForm() {
        String title = jtfTitle.getText();
        String language = jtfLanguage.getText();
        String authorsField = authors.toString();
        try {
            short year = Short.parseShort(jtfYear.getText());
            byte volume = Byte.parseByte(jtfVolume.getText());
            long isbn = Long.parseLong(jtfIsbn.getText());
            short pages = Short.parseShort(jtfPages.getText());
        } catch (NumberFormatException ex) {
            GUIMessage.error("Fill all the fields with real values.");
            return true;
        }
        if (title.isEmpty()) {
            GUIMessage.error("The title field can not be null.");
            return true;
        }
        if ("[]".equals(authorsField)) {
            GUIMessage.error("Add some author for this book.");
            return true;
        }
        if (jtfYear.getText().isEmpty()) {
            GUIMessage.error("The year field can not be null.");
            return true;
        }
        if (jtfVolume.getText().isEmpty()) {
            GUIMessage.error("The volume field can not be null.");
            return true;
        }
        if (language.isEmpty()) {
            GUIMessage.error("The language field can not be null.");
            return true;
        }
        if (jtfIsbn.getText().isEmpty()) {
            GUIMessage.error("The ISBN field can not be null.");
            return true;
        }
        if (jtfPages.getText().isEmpty()) {
            GUIMessage.error("The pages field can not be null.");
            return true;
        }
        return false;
    }

    private void clearForm() {
        jtfTitle.setText("");
        jtfYear.setText("");
        jtfVolume.setText("");
        jtfLanguage.setText("");
        jtfIsbn.setText("");
        jtfPages.setText("");
        //authors.clear();
    }

    private void jbCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCloseActionPerformed
        //dispose();
        //this.dispose();
        AddBookForm.this.setVisible(false);
        //this.MainWindowForm.setVisible(true);
    }//GEN-LAST:event_jbCloseActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {
        //dispose();
        //this.dispose();
        AddBookForm.this.setVisible(false);
        //this.MainWindowForm.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jbAddAuthor;
    private javax.swing.JButton jbClose;
    private javax.swing.JButton jbOk;
    private javax.swing.JTextField jtfIsbn;
    private javax.swing.JTextField jtfLanguage;
    private javax.swing.JTextField jtfPages;
    private javax.swing.JTextField jtfTitle;
    private javax.swing.JTextField jtfVolume;
    private javax.swing.JTextField jtfYear;
    // End of variables declaration//GEN-END:variables
}
